config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "chatroom#index"
  get "login", to: "sessions#new"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(30) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: { case_sensitive: false }, presence: true, length: { minimum: 3, maximum: 15 }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:error] = "You must be logged in to perform this action."
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user
    def index
        @message = Message.new
        @messages = Message.custom_display
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast 'chatroom_channel',
                                         incoming_message: message_render(message)
        end
    end

    private

    def message_params
        params.require(:message).permit(:body)
    end

    def message_render(msg)
        render(partial: 'message', locals: {message: msg})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]
    def new
    end
    
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Successfully logged in"
            redirect_to root_path
        else
            flash.now[:error] = "Invalid credentials"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have successfully logged out"
        redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are already logged in"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
`<h4 class="ui center aligned medium icon header">
  <i class="circular orange envelope icon"></i>
  Say Something
</h4>


<div class="ui two column grid">
    <div class="twelve wide column" >
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui feed" id="message-container">
                    <%# <div class="event">
                        <div class="content">
                            <div class="summary">
                                <a>Elliot Fu</a> added <a>Jenny Hess</a> as a friend
                            </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                        <div class="summary">
                            <a>Stevie Feliciano</a> added <a>Elliot Fu</a> as a friend
                        </div>
                        </div>
                    </div>
                    <div class="event">
                        <div class="content">
                        <div class="summary">
                            <a>Helen Troy</a> added <a>Christian Rocha</a> as a friend
                        </div>
                        </div>
                    </div> %>
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class: "Ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
                    <div class="field">
                        <div class="ui fluid icon input">
                            <%= f.text_field :body %>
                            <%= f.button '<i class="bordered inverted orange paper plane icon"></i>'.html_safe %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>

    <div class="four wide column" >
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                    <a class="active item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
    <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
        <%= message_content %>
    </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
    <div class = "ui container" >
        <a class="item" href="/">
            Chatroom
        </a>
        <a class="item">
            Messages
        </a>
        <div class="right menu">
            <div class="ui dropdown item">
                Account <i class="dropdown icon"></i>
                <div class="menu">
                    <% if logged_in? %>
                        <%= link_to "Log out", logout_path, data: { turbo_method: :delete}, class: "item"%>
                    <% else %>
                        <%= link_to "Log in", login_path, class: "item"%>
                        <%# <a class="item">Sign up</a> %>
                    <% end %>
                </div>
            </div>
            <% if !logged_in? %>
            <div class="item">
                <%= link_to "Log in", login_path, class: "ui primary button"%>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.js"></script>
    <script>
        $(document).ready(function () {
          $(".ui.dropdown").dropdown();
          $('.message .close').on('click', function() {
              $(this)
                .closest('.message')
                .transition('fade');
            });
          scroll_bottom();
          submit_message();
        });
        submit_message = function() {
          $('#message_body').on('keydown', function(e) {
            if (e.keyCode == 13) {
              $('button').click();
              e.target.value = "";
            }
          })
        }
        scroll_bottom = function() {
          if ($('#messages').length > 0) {
            $('#messages').scrollTop($('#messages')[0].scrollHeight);
          }
        }
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag%>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class = "ui container" >
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div>